app = "neogrok-demo-zoekt"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile.zoekt"

[env]

[experimental]
  auto_rollback = true

[checks]
  [checks.tcp_check]
    type = "tcp"
    port = 8080
    grace_period = "1s"
    interval = "15s"
    timeout = "2s"
